Added changes for Pattern-1
wso2-incubator/wso2am-k8s-operator pull request #64
Opened 2020-12-01 10:04 UTC by BLasan

- Removed MySQL PVC
- Added Headless Service for Worker-Analytics
- Added 'AllowAnalytics' field in types.go

2020-12-02 08:13 UTC, pubudu538 requested changes

2020-12-02 08:13 UTC, pubudu538 commented on artifacts/api-manager-artifacts/pattern-1/wso2am-p1-apim-1-conf.yaml
> +    enable = "$env{ALLOW_ANALYTICS}"
THis should be enable analytics.

2020-12-02 11:45 UTC, BLasan commented
@pubudu538  Please review

2020-12-07 08:17 UTC, pubudu538 commented on pkg/apis/apim/v1alpha1/types.go
> +	Allownalytics string    `json:"enableAnalytics"`
Let's use the same enableAnalytics in here as well.

2020-12-07 08:56 UTC, pubudu538 approved these changes

2020-12-07 08:56 UTC, merged

2022-12-01 11:48 UTC, GDLMadushanka commented on pkg/controller/controller.go
> +				// workerdeployment, err = c.kubeclientset.AppsV1().Deployments(apimanager.Namespace).Create(pattern1.WorkerDeployment(apimanager, y, worknum))
remove comments

2023-01-19 03:16 UTC, BLasan commented on pkg/controller/controller.go
> +				// workerdeployment, err = c.kubeclientset.AppsV1().Deployments(apimanager.Namespace).Create(pattern1.WorkerDeployment(apimanager, y, worknum))
fixed via https://github.com/BLasan/k8s-wso2am-operator/commit/8b163758448b29fec66bc8139ad184f405bf1f28